'''
convert the *.caffemodel generated by DNS to compressed format.
'''

import sys
import os
import numpy as np
#  import caffe_pb2

compressed_model = "cmprd.model"

# TODO: 
help_ ='''
Usage:
    dns_model_compress.py <source.caffemodel> <target.cmodel>
    Set the CAFFE_ROOT in the source file.
'''
#######################################################

try:
    argv_list = list(sys.argv)
    prototxt_file = argv_list[1]
    caffemodel = argv_list[2]
except IndexError as e:
    print e
    sys.exit()

if not os.path.exists(caffemodel):
    print "Error: caffemodel does NOT exist!"
    sys.exit()
elif not os.path.exists(prototxt_file):
    print "Error: prototxt file does NOT exist!"
    sys.exit()
    

net = caffe.Net(prototxt_file, caffemodel, caffe.TEST)

f = open(compressed_model, 'wb')

# with open(compressed_model, 'wb') as f:

for param_name in net.params.keys():
    if 'conv' in param_name:
        pass
    elif ('ip' in param_name or 'fc' in param_name):
        pass
    else:
        pass


